# This workflow will build and deploy Lambda

name: Building and Deploying Lambda Function

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
    
jobs:
  build:
    name: Build_Lambda
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
       
    steps:
    - uses: actions/checkout@v3
    - name: Creating a zip file for lambda
      run: |
           pwd
           ls -al
           zip -r index.zip ./
           echo "after zipping index folder"
           ls -al
    - name: Configuring AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}
        aws-region: us-east-1
    - name: Copying artifact to S3
      run: |
           aws s3 cp ./index.zip s3://deploy.serverless.as09/
    - name: Lambda Update
      run: |
           aws lambda update-function-code --function-name emailVerify --s3-bucket deploy.serverless.as09 --s3-key index.zip
